[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my_awesome_package"
version = "0.1.0"
authors = [
  { name="Jules", email="jules@example.com" },
]
description = "A bootstrapped python package that supports multiple OS and Architectures."
readme = "README.md"
requires-python = ">=3.11, <3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
]

[project.urls]
"Homepage" = "https://github.com/example/my_awesome_package"

[project.scripts]
my-awesome-script = "my_awesome_package.cli:main"
my-other-script = "my_awesome_package.cli:main2"
